/*
 * File: app/store/MenuStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ortodont.store.MenuStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ortodont.model.MenuModel',
        'Ext.data.proxy.Memory'
    ],

    config: {
        data: [
            {
                id: 1,
                text: 'Home'
            },
            {
                id: 2,
                text: 'Prices'
            },
            {
                id: 3,
                text: 'Login'
            }
        ],
        model: 'Ortodont.model.MenuModel',
        storeId: 'MenuStore',
        proxy: {
            type: 'memory'
        }
    }
});